DROP TABLE IF EXISTS movies;
CREATE TABLE movies(
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  year INTEGER NOT NULL,
  runtime INTEGER NOT NULL,
  genres TEXT[] NOT NULL,
  created TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);